#!/bin/sh

TESTDIR="${TESTDIR:-.}"
TMPFILE=out.tmp
TMPFILE2=out2.tmp
TOKEN="--token=279396402074015764735041244773131252103253001721722151344173126350250236671677634"
STOKEN="${STOKEN:-../stoken}"
if ! test -z "${VALGRIND}";then
VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
fi

rm -f $TMPFILE

$VALGRIND $STOKEN export $TOKEN --android >$TMPFILE
if test $? != 0;then
	echo "cmd 1 failed"
	exit 1
fi

grep "http://127.0.0.1/securid/ctf?ctfData=279396402074015764735041244773131252103253001721722151344173126350250236671677634$" $TMPFILE >/dev/null 2>&1
if test $? != 0;then
	echo "test 1 failed"
	exit 1
fi

$VALGRIND $STOKEN export $TOKEN --v3 >$TMPFILE
if test $? != 0;then
	echo "cmd 2 failed"
	exit 1
fi

grep "http://127.0.0.1/securid/ctf?ctfData=Aw" $TMPFILE >/dev/null 2>&1
if test $? != 0;then
	echo "test 2 failed"
	exit 1
fi

$VALGRIND $STOKEN export $TOKEN --iphone --new-password asdf >$TMPFILE
if test $? != 0;then
	echo "cmd 3 failed"
	exit 1
fi

grep "com.rsa.securid.iphone://ctf?ctfData=279396402074014034342410542127366277612253543712524336266173126350250236671647665$" $TMPFILE >/dev/null 2>&1
if test $? != 0;then
	echo "test 3 failed"
	cat $TMPFILE
	exit 1
fi

$VALGRIND $STOKEN export $TOKEN --sdtid \
	--template $TESTDIR/fixed-secret.xml \
	--new-devid 'a01c4380-fc01-4df0-b113-7fb98ec74694' \
	--new-password 'Correct_horse!battery&staple' >$TMPFILE
if test $? != 0;then
	echo "cmd 4 failed"
	exit 1
fi

cmp $TMPFILE $TESTDIR/devid-passwd.sdtid
if test $? != 0;then
	echo "test 4 failed"
	cat $TMPFILE
	exit 1
fi

$VALGRIND $STOKEN export --v3 --file $TESTDIR/pinmode-2.sdtid >$TMPFILE
if test $? != 0;then
	echo "cmd 5(a) failed"
	exit 1
fi

$VALGRIND $STOKEN export --file $TMPFILE --sdtid \
	--template $TESTDIR/fixed-secret.xml >$TMPFILE2
if test $? != 0;then
	echo "cmd 5(b) failed"
	exit 1
fi

cmp $TMPFILE2 $TESTDIR/pinmode-2.sdtid
if test $? != 0;then
	echo "test 5 failed"
	cat $TMPFILE2
	exit 1
fi

rm -f $TMPFILE $TMPFILE2

exit 0

